name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -t frontend:latest ./frontend
          docker build -t backend:latest ./backend
          docker build -t orders:latest ./orders
          docker build -t nginx:latest ./nginx

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start backend
        run: |
          docker compose up -d backend
          sleep 5

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/api/products; then
              echo "Backend is ready"
              break
            fi
            echo "Waiting for backend..."
            sleep 3
          done

      - name: Install dependencies and run tests
        run: |
          pip install -r backend/requirements.txt
          pip install pytest
          pytest backend/tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --build
